### ISSUE TITLE
Error in preparation of GNPS files

### ISSUE THREAD

**Issue by RachelGregor** [askerdb/rCSCS#1]
Hello, 

Looking forward to trying this out but ran into some issues getting my data into it:

1) Is this available for GNPS jobs created using MZmine? These do not have a bucket table to download and result in an error.

2) I tried it with a GNPS job (ID =9144d1b70a7249809f94ef85d73ee5bb), and got the following error:

Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 1 did not have 8 elements

I think that the edge file has an extra column in it that does not appear in the tutorial, "EdgeAnnotation". 

Can I manually select the necessary files? In general this would be useful (for example to edit in Cytoscape first). 

Thank you!

Best, 
Rachel

**Comment by askerdb** [comment]
Hi Rachel,

Thanks for trying this out and taking the time to make this bug report!

1) We have not included an MZMine workflow for now, but we will get around to it. If you produce a feature table from MZMine it is essentially about downloading the edges table from GNPS, loading the feature table and making sure those two are ordered the same, then running the cscs() function. I will get back to you when we make a guide!

2) GNPS had constructed a file with a colum of all spaces. This is a problem because we use read.table() with the default separator, which is all whitespace, so it thinks both tabs and spaces are a separator. I have fixed that, if you re-install it should load your data:
```

rCSCS::download_edges("9144d1b70a7249809f94ef85d73ee5bb")
css <- rCSCS:::prepare_css("edges_file.txt") 
```

I'm not entirely certain about your last question, how do you want to select?

Asker

**Comment by RachelGregor** [comment]
Hi there, 

Awesome, thanks for the quick reply and fix! It downloads just fine now.

By manually selecting, I mean being able to upload the edges and feature table manually (like I see is implemented in the Q2 workflow), rather than downloading directly from GNPS, so you can filter beforehand for example. But if there's an MZmine option, that should solve that issue mostly, because then it can be filtered in MZmine prior to making a network. 

Looking forward to running this!

Best, 
Rachel

**Comment by askerdb** [comment]
Hi Rachel,

You can always simply call the cscs() function with data you imported yourself as normal matrices. The only requirement is that there must be the same number of features in both the intensity table and the CSS table, and they must be ordered the same way. The MZMine tutorial should demonstrate how to do this when done!

Asker

**Comment by RachelGregor** [comment]
Hi Asker,

Great, wasn’t sure if the prepare_GNPS function was doing anything special
to the data beforehand... thank you! I’ll give it a try.

Best,
Rachel
